name: pages build and deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write  # <--- VERY IMPORTANT!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # make sure index.html is directly inside repo
